name:                example
version:             0.0.0.0
github:              "logicoffee/example"
license:             BSD3
author:              "logicoffee"
maintainer:          "example@example.com"
copyright:           "2022 logicoffee"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/logicoffee/haskell-purescript-example>

dependencies:
- base >= 4.7 && < 5
- aeson
- beam-core
- beam-sqlite
- bytestring
- http-media
- optparse-applicative
- random-shuffle
- servant
- servant-blaze
- servant-server
- sqlite-simple
- text
- turtle
- warp
- wai-logger

library:
  source-dirs: src

executables:
  app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example
  cli:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example
